name: project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0 
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  flutter_datetime_picker: 1.5.1
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^9.9.0
  fluttertoast: ^8.2.2
  http: ^0.13.4
  modal_progress_hud_nsn: ^0.4.0
  socket_io_client: ^2.0.2
  intl: ^0.17.0
  agora_rtc_engine: 
  permission_handler: ^9.2.0
  rive: ^0.11.4
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/onboardingScreen/
    - assets/avaters/
    - assets/icons/
    - assets/RiveAssets/

fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700